#!/usr/bin/env bash
# printing "Best School" 10 times except on iteration 9

count=0

until [ $count -ge 10 ]; do
    if [ $count -eq 8 ]; then
        echo "Best School"
	echo "Hi"
    else
        echo "Best School"
    fi
    ((count++))
done
