#!/usr/bin/env bash
# printing "Best School" 10 times except iteration 4 and iteration 8
count=0

while [ $count -lt 10 ]; do
    if [ $count -eq 3 ]; then
        echo "bad luck"
    elif [ $count -eq 7 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((count++))
done
