#!/usr/bin/env bash
# This script runs Nginx as Nginx

sudo sed -i "s/user www-data/user" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sitess-available/default
sudo chmod 664 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
